RETWEET_WORDING = 'retweet'
REPOST_WORDING = 'repost'
CITATION_WORDING = 'quote'
LIKE_WORDING = 'like'
BOOKMARK_WORDING = 'bookmark'
CITE_WORDING = '/status/'

TWEET_ID_PROPERTY = 'tweet_id'
SOURCE_NAME_PROPERTY = 'source_name'
USERNAME_PROPERTY = 'username'
IS_VERIFIED_PROPERTY = 'is_verified'
CONTENT_PROPERTY = 'content'
TWEET_ID_CITATION = 'citing_tweet_id'
USERNAME_CITING_TO = 'citing_to_user'
LANGUAGE_PROPERTY = 'language'
RETWEETS_PROPERTY = 'retweets'
LIKES_PROPERTY = 'likes'
CITATIONS_PROPERTY = 'citations'
BOOKMARKS_PROPERTY = 'bookmarks'
IS_RETWEET_PROPERTY = 'is_retweet'
RETWEETER_PROPERTY = 'retweeter'
TWEET_ID_RETWEETED_PROPERTY = 'tweet_id_retweeted'

PUBLISH_TIME_PROPERTY = 'publish_time'

NO_LANGUAGE = 'no_lang'